[package]
name = "bips-dev"
version = "0.1.0"
authors = ["ngmiller <nick@ngmiller.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1"
parse-wiki-text-2 = "0.1.6-alpha.0"
regex = "1"
