base_url = "https://bips.dev"

ignored_content = [ "*-wordlists.md", "**/bip-*/**/*.md" ]
taxonomies = [
    { name = "authors" },
    { name = "status" }
]

[markdown]
external_links_target_blank = true

[link_checker]
internal_level = "warn"

[slugify]
anchors = "off"
